POST /api/2.4/contracts/05285a1b38494dcaaf0e47408f5913f9/documents?acc_token=20d3ef355ba342caaacd6590d712c6eb HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 199
Content-Type: multipart/form-data; boundary=----------a_BoUnDaRy631810785883$
Host: api-sandbox.openprocurement.org

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.4/contracts/05285a1b38494dcaaf0e47408f5913f9/documents/0200c8217aef4e1c83f8360503b716cc
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "title": "contract_changes.doc", 
    "url": "http://public.docs-sandbox.openprocurement.org/get/7882203e7dd2449b856fb16794b40871?KeyID=f988f514&Signature=csn2SA0Ek1NCRBlkQg2ScezTysfJgdml5SRGjU3jAcrhq5e%2FSNu5hsUSf6f5VIJgiCIP8PxPdf8NiLOv%2FMmHBg%253D%253D", 
    "format": "application/msword", 
    "documentOf": "contract", 
    "datePublished": "2018-05-15T15:33:43.835245+03:00", 
    "id": "0200c8217aef4e1c83f8360503b716cc", 
    "dateModified": "2018-05-15T15:33:43.835277+03:00"
  }
}

