GET /api/2.4/contracts/05285a1b38494dcaaf0e47408f5913f9 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "period": {
      "startDate": "2018-05-23T09:37:39.577948+03:00", 
      "endDate": "2022-05-23T09:37:39.577948+03:00"
    }, 
    "procuringEntity": {
      "contactPoint": {
        "email": "e.zhogan@ksteplo.com.ua", 
        "telephone": "+380933907440", 
        "availableLanguage": "en", 
        "name": "ТОВАРИСТВО З ОБМЕЖЕНОЮ ВІДПОВІДАЛЬНІСТЮ \"ЄВРОПЕЙСЬКА ЕНЕРГОСЕРВІСНА КОМПАНІЯ\""
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "40957551", 
        "legalName": "ТОВАРИСТВО З ОБМЕЖЕНОЮ ВІДПОВІДАЛЬНІСТЮ \"ЄВРОПЕЙСЬКА ЕНЕРГОСЕРВІСНА КОМПАНІЯ\""
      }, 
      "name": "ТОВАРИСТВО З ОБМЕЖЕНОЮ ВІДПОВІДАЛЬНІСТЮ \"ЄВРОПЕЙСЬКА ЕНЕРГОСЕРВІСНА КОМПАНІЯ\"", 
      "address": {
        "postalCode": "", 
        "countryName": "Україна", 
        "streetAddress": "01004, м.Київ, БЕССАРАБСЬКА ПЛОЩА, будинок 9/1 Б, офіс 2", 
        "region": "", 
        "locality": ""
      }, 
      "additionalContactPoints": [
        {
          "name": "Державне управління справами2", 
          "telephone": "0440000001"
        }
      ]
    }, 
    "owner": "broker", 
    "id": "05285a1b38494dcaaf0e47408f5913f9", 
    "tender_id": "4f3f52df56274163b5cf22a00cd71478", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "title": "contract_changes.doc", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/8eb69ce6ba9a4a2d8b88896e044ec33c?KeyID=a4f1bd8c&Signature=1zwKSb%252BoFvaANPSDNiiuGOldad5b%2F60GxkzEVXp94vW%252BxfullpS6oV0MSf02m%2FIxFIHc2ka78W82OYUovFHSCQ%253D%253D", 
        "format": "application/msword", 
        "documentOf": "change", 
        "datePublished": "2018-05-23T09:37:42.564053+03:00", 
        "id": "daafead1c21b43dcb7dfebbeaaacdfa1", 
        "relatedItem": "2012fa38548546dcbda1601ce90c91bb", 
        "dateModified": "2018-05-23T09:37:42.564083+03:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "title": "contract.doc", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/c0e452839f834d68965b3a02a1c6413d?KeyID=a4f1bd8c&Signature=PAhwnmC4kKkPFrA7M7PEbfJktSU%2FN62HQHFWJYL%2FFNlCSNuHgtm2VGDPHTlLuHpMGt5QxJRkEXCyJNlNfMIbDA%253D%253D", 
        "format": "application/msword", 
        "documentOf": "contract", 
        "datePublished": "2018-05-23T09:37:44.296267+03:00", 
        "id": "6594bbd6fcb54180b4a6d59ae63864ae", 
        "dateModified": "2018-05-23T09:37:44.296294+03:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "title": "contract_additional_docs.doc", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/7ad5367892fe4b979f7ffc3fcf13f82a?KeyID=a4f1bd8c&Signature=xRgZF6IA07IS%252BT6IhVa8MyE1Acsouqd4OO%252BjDWlk0F0HAOhg0GXctbtt8sx6xINAYxirKqGNwhvnEv6zfMRwCw%253D%253D", 
        "format": "application/msword", 
        "documentOf": "contract", 
        "datePublished": "2018-05-23T09:37:44.454405+03:00", 
        "id": "97f13f29e49342d1bc9d1847f7b2ec4e", 
        "dateModified": "2018-05-23T09:37:44.454434+03:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "title": "contract_additional_docs.doc", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/fedc409919d94c4bbb1f1194d2f0660f?KeyID=a4f1bd8c&Signature=CQVfQtIIB3NjY2kqIzsZufZ18vCdoUNq8K%2Fwv7jTPxZvDr8xx46AbYVOJ9JP88Vxae35Mz9vB1MIme6Yrug%252BCg%253D%253D", 
        "format": "application/msword", 
        "documentOf": "contract", 
        "datePublished": "2018-05-23T09:37:44.454405+03:00", 
        "id": "97f13f29e49342d1bc9d1847f7b2ec4e", 
        "dateModified": "2018-05-23T09:37:44.566759+03:00"
      }
    ], 
    "title": "Енергосервіс будівлі Комунальної установи Сумська загальноосвітня школа І-ІІІ ступенів № 26 м.Суми, Сумсбкої області", 
    "contractNumber": "17", 
    "dateModified": "2018-05-23T09:37:45.339660+03:00", 
    "status": "active", 
    "description": "", 
    "NBUdiscountRate": 0.135, 
    "dateSigned": "2018-05-23T09:37:39.577948+03:00", 
    "contractType": "esco", 
    "amountPaid": {
      "currency": "UAH", 
      "amount": 320000.0, 
      "valueAddedTaxIncluded": true
    }, 
    "milestones": [
      {
        "status": "met", 
        "description": "Milestone #1 of year 2018", 
        "sequenceNumber": 1, 
        "title": "Milestone #1 of year 2018", 
        "period": {
          "startDate": "2018-05-23T09:37:39.577948+03:00", 
          "endDate": "2019-01-01T00:00:00+02:00"
        }, 
        "value": {
          "currency": "UAH", 
          "amount": 0, 
          "valueAddedTaxIncluded": true
        }, 
        "id": "44770bd916b14d5ab6d9eea0527e5e20", 
        "date": "2018-05-23T09:37:44.772057+03:00", 
        "amountPaid": {
          "currency": "UAH", 
          "amount": 0, 
          "valueAddedTaxIncluded": true
        }, 
        "dateModified": "2018-05-23T09:37:44.772057+03:00"
      }, 
      {
        "status": "met", 
        "description": "Milestone #2 of year 2019", 
        "sequenceNumber": 2, 
        "title": "Milestone #2 of year 2019", 
        "period": {
          "startDate": "2019-01-01T00:00:00+02:00", 
          "endDate": "2020-01-01T00:00:00+02:00"
        }, 
        "value": {
          "currency": "UAH", 
          "amount": 80000.0, 
          "valueAddedTaxIncluded": true
        }, 
        "id": "74ed371ed450417caed14aaf2ab6687b", 
        "date": "2018-05-23T09:37:45.019170+03:00", 
        "amountPaid": {
          "currency": "UAH", 
          "amount": 240000.0, 
          "valueAddedTaxIncluded": true
        }, 
        "dateModified": "2018-05-23T09:37:45.019170+03:00"
      }, 
      {
        "status": "partiallyMet", 
        "description": "Milestone #3 of year 2020", 
        "sequenceNumber": 3, 
        "title": "Milestone #3 of year 2020", 
        "period": {
          "startDate": "2020-01-01T00:00:00+02:00", 
          "endDate": "2021-01-01T00:00:00+02:00"
        }, 
        "value": {
          "currency": "UAH", 
          "amount": 80000.0, 
          "valueAddedTaxIncluded": true
        }, 
        "id": "6cab1f95bb904a2183e2f0de1f0a6063", 
        "date": "2018-05-23T09:37:45.141633+03:00", 
        "amountPaid": {
          "currency": "UAH", 
          "amount": 40000.0, 
          "valueAddedTaxIncluded": true
        }, 
        "dateModified": "2018-05-23T09:37:45.141633+03:00"
      }, 
      {
        "status": "partiallyMet", 
        "description": "Milestone #4 of year 2021", 
        "sequenceNumber": 4, 
        "title": "Milestone #4 of year 2021", 
        "period": {
          "startDate": "2021-01-01T00:00:00+02:00", 
          "endDate": "2022-01-01T00:00:00+02:00"
        }, 
        "value": {
          "currency": "UAH", 
          "amount": 80000.0, 
          "valueAddedTaxIncluded": true
        }, 
        "id": "7ab535cad7ef4516bfa9c6f18608bb50", 
        "date": "2018-05-23T09:37:45.326186+03:00", 
        "amountPaid": {
          "currency": "UAH", 
          "amount": 40000.0, 
          "valueAddedTaxIncluded": true
        }, 
        "dateModified": "2018-05-23T09:37:45.326186+03:00"
      }, 
      {
        "status": "pending", 
        "description": "Milestone #5 of year 2022", 
        "sequenceNumber": 5, 
        "title": "Milestone #5 of year 2022", 
        "period": {
          "startDate": "2022-01-01T00:00:00+02:00", 
          "endDate": "2022-05-23T09:37:39.577948+03:00"
        }, 
        "value": {
          "currency": "UAH", 
          "amount": 80000.0, 
          "valueAddedTaxIncluded": true
        }, 
        "id": "981bd581b42b4e5ea9822d8af43d794d", 
        "date": "2018-05-23T09:37:45.326186+03:00", 
        "amountPaid": {
          "currency": "UAH", 
          "amount": 0, 
          "valueAddedTaxIncluded": true
        }, 
        "dateModified": "2018-05-23T09:37:45.326186+03:00"
      }
    ], 
    "items": [
      {
        "description": "ЕНергосервіс будівлі Комунальної установи Сумська загальноосвітня школа І-ІІІ ступенів № 26 м. Суми, Сумської області", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Не відображене в інших розділах", 
          "id": "99999999-9"
        }, 
        "description_en": "Energy service of the public institution building of Sumy secondary school Nr 26", 
        "additionalClassifications": [
          {
            "scheme": "specialNorms", 
            "id": "000", 
            "description": "Специальные нормы и другое"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "40007", 
          "countryName": "Україна", 
          "streetAddress": "Охтирська, 21", 
          "region": "Сумська обл.", 
          "locality": "Суми"
        }, 
        "id": "660e66a4ffd0486f8f90041f36105f05", 
        "quantity": 2
      }
    ], 
    "suppliers": [
      {
        "contactPoint": {
          "email": "e.zhogan@ksteplo.com.ua", 
          "telephone": "+380933907440", 
          "name": "ТОВАРИСТВО З ОБМЕЖЕНОЮ ВІДПОВІДАЛЬНІСТЮ \"ЄВРОПЕЙСЬКА ЕНЕРГОСЕРВІСНА КОМПАНІЯ\""
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "40957551", 
          "legalName": "ТОВАРИСТВО З ОБМЕЖЕНОЮ ВІДПОВІДАЛЬНІСТЮ \"ЄВРОПЕЙСЬКА ЕНЕРГОСЕРВІСНА КОМПАНІЯ\""
        }, 
        "name": "ТОВАРИСТВО З ОБМЕЖЕНОЮ ВІДПОВІДАЛЬНІСТЮ \"ЄВРОПЕЙСЬКА ЕНЕРГОСЕРВІСНА КОМПАНІЯ\"", 
        "address": {
          "postalCode": "", 
          "countryName": "Україна", 
          "streetAddress": "01004, м.Київ, БЕССАРАБСЬКА ПЛОЩА, будинок 9/1 Б, офіс 2", 
          "region": "", 
          "locality": ""
        }
      }
    ], 
    "value": {
      "yearlyPaymentsPercentage": 0.92, 
      "valueAddedTaxIncluded": true, 
      "currency": "UAH", 
      "amount": 320000.0, 
      "contractDuration": {
        "days": 310, 
        "years": 6
      }, 
      "amountPerformance": 446471.27, 
      "annualCostsReduction": [
        0, 
        178997.04, 
        225643.72, 
        225643.72, 
        225643.72, 
        225643.72, 
        225643.72, 
        225643.72, 
        141782.47, 
        141782.47, 
        141782.47, 
        141782.47, 
        141782.47, 
        141782.47, 
        141782.47, 
        141782.47, 
        141782.47, 
        141782.47, 
        141782.47, 
        141782.47, 
        141782.47
      ]
    }, 
    "awardID": "29c01dd058c347f38e381f13d4a6a118", 
    "changes": [
      {
        "status": "active", 
        "rationaleTypes": [
          "volumeCuts", 
          "priceReduction"
        ], 
        "rationale_en": "Contract change cause", 
        "dateSigned": "2018-05-23T09:37:44.046886+03:00", 
        "rationale": "Друга і третя поставка має бути розфасована", 
        "date": "2018-05-23T09:37:44.097032+03:00", 
        "id": "2012fa38548546dcbda1601ce90c91bb"
      }
    ], 
    "contractID": "UA-2017-11-21-001567-c-a1"
  }
}

