PATCH /api/2.4/contracts/05285a1b38494dcaaf0e47408f5913f9/credentials?acc_token=e60d286e5c6f43a990679660da817aec HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 0
Content-Type: application/json
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "access": {
    "token": "a8a4bcfba9ca45edb7bd7c99e651804b"
  }, 
  "data": {
    "status": "active", 
    "milestones": [
      {
        "status": "pending", 
        "description": "Milestone #1 of year 2018", 
        "sequenceNumber": 1, 
        "title": "Milestone #1 of year 2018", 
        "period": {
          "startDate": "2018-05-23T09:37:39.577948+03:00", 
          "endDate": "2019-01-01T00:00:00+02:00"
        }, 
        "value": {
          "currency": "UAH", 
          "amount": 0, 
          "valueAddedTaxIncluded": true
        }, 
        "id": "44770bd916b14d5ab6d9eea0527e5e20", 
        "date": "2018-05-23T09:37:39.579547+03:00", 
        "amountPaid": {
          "currency": "UAH", 
          "amount": 0, 
          "valueAddedTaxIncluded": true
        }, 
        "dateModified": "2018-05-23T09:37:39.579547+03:00"
      }, 
      {
        "status": "scheduled", 
        "description": "Milestone #2 of year 2019", 
        "sequenceNumber": 2, 
        "title": "Milestone #2 of year 2019", 
        "period": {
          "startDate": "2019-01-01T00:00:00+02:00", 
          "endDate": "2020-01-01T00:00:00+02:00"
        }, 
        "value": {
          "currency": "UAH", 
          "amount": 164677.28, 
          "valueAddedTaxIncluded": true
        }, 
        "id": "74ed371ed450417caed14aaf2ab6687b", 
        "date": "2018-05-23T09:37:39.579686+03:00", 
        "amountPaid": {
          "currency": "UAH", 
          "amount": 0, 
          "valueAddedTaxIncluded": true
        }, 
        "dateModified": "2018-05-23T09:37:39.579686+03:00"
      }, 
      {
        "status": "scheduled", 
        "description": "Milestone #3 of year 2020", 
        "sequenceNumber": 3, 
        "title": "Milestone #3 of year 2020", 
        "period": {
          "startDate": "2020-01-01T00:00:00+02:00", 
          "endDate": "2021-01-01T00:00:00+02:00"
        }, 
        "value": {
          "currency": "UAH", 
          "amount": 207592.22, 
          "valueAddedTaxIncluded": true
        }, 
        "id": "6cab1f95bb904a2183e2f0de1f0a6063", 
        "date": "2018-05-23T09:37:39.579846+03:00", 
        "amountPaid": {
          "currency": "UAH", 
          "amount": 0, 
          "valueAddedTaxIncluded": true
        }, 
        "dateModified": "2018-05-23T09:37:39.579846+03:00"
      }, 
      {
        "status": "scheduled", 
        "description": "Milestone #4 of year 2021", 
        "sequenceNumber": 4, 
        "title": "Milestone #4 of year 2021", 
        "period": {
          "startDate": "2021-01-01T00:00:00+02:00", 
          "endDate": "2022-01-01T00:00:00+02:00"
        }, 
        "value": {
          "currency": "UAH", 
          "amount": 207592.22, 
          "valueAddedTaxIncluded": true
        }, 
        "id": "7ab535cad7ef4516bfa9c6f18608bb50", 
        "date": "2018-05-23T09:37:39.579998+03:00", 
        "amountPaid": {
          "currency": "UAH", 
          "amount": 0, 
          "valueAddedTaxIncluded": true
        }, 
        "dateModified": "2018-05-23T09:37:39.579998+03:00"
      }, 
      {
        "status": "scheduled", 
        "description": "Milestone #5 of year 2022", 
        "sequenceNumber": 5, 
        "title": "Milestone #5 of year 2022", 
        "period": {
          "startDate": "2022-01-01T00:00:00+02:00", 
          "endDate": "2023-01-01T00:00:00+02:00"
        }, 
        "value": {
          "currency": "UAH", 
          "amount": 207592.22, 
          "valueAddedTaxIncluded": true
        }, 
        "id": "981bd581b42b4e5ea9822d8af43d794d", 
        "date": "2018-05-23T09:37:39.580154+03:00", 
        "amountPaid": {
          "currency": "UAH", 
          "amount": 0, 
          "valueAddedTaxIncluded": true
        }, 
        "dateModified": "2018-05-23T09:37:39.580154+03:00"
      }, 
      {
        "status": "scheduled", 
        "description": "Milestone #6 of year 2023", 
        "sequenceNumber": 6, 
        "title": "Milestone #6 of year 2023", 
        "period": {
          "startDate": "2023-01-01T00:00:00+02:00", 
          "endDate": "2024-01-01T00:00:00+02:00"
        }, 
        "value": {
          "currency": "UAH", 
          "amount": 207592.22, 
          "valueAddedTaxIncluded": true
        }, 
        "id": "230506b59daa49e6955a2fd24e8e3678", 
        "date": "2018-05-23T09:37:39.580302+03:00", 
        "amountPaid": {
          "currency": "UAH", 
          "amount": 0, 
          "valueAddedTaxIncluded": true
        }, 
        "dateModified": "2018-05-23T09:37:39.580302+03:00"
      }, 
      {
        "status": "scheduled", 
        "description": "Milestone #7 of year 2024", 
        "sequenceNumber": 7, 
        "title": "Milestone #7 of year 2024", 
        "period": {
          "startDate": "2024-01-01T00:00:00+02:00", 
          "endDate": "2025-01-01T00:00:00+02:00"
        }, 
        "value": {
          "currency": "UAH", 
          "amount": 207592.22, 
          "valueAddedTaxIncluded": true
        }, 
        "id": "48f79c3de16e41ef9db179c804ee560c", 
        "date": "2018-05-23T09:37:39.580449+03:00", 
        "amountPaid": {
          "currency": "UAH", 
          "amount": 0, 
          "valueAddedTaxIncluded": true
        }, 
        "dateModified": "2018-05-23T09:37:39.580449+03:00"
      }, 
      {
        "status": "scheduled", 
        "description": "Milestone #8 of year 2025", 
        "sequenceNumber": 8, 
        "title": "Milestone #8 of year 2025", 
        "period": {
          "startDate": "2025-01-01T00:00:00+02:00", 
          "endDate": "2025-03-29T09:37:39.577948+03:00"
        }, 
        "value": {
          "currency": "UAH", 
          "amount": 50049.63, 
          "valueAddedTaxIncluded": true
        }, 
        "id": "1bb4c23f7f2943678256354506f182c8", 
        "date": "2018-05-23T09:37:39.580594+03:00", 
        "amountPaid": {
          "currency": "UAH", 
          "amount": 0, 
          "valueAddedTaxIncluded": true
        }, 
        "dateModified": "2018-05-23T09:37:39.580594+03:00"
      }
    ], 
    "description": "", 
    "title": "Енергосервіс будівлі Комунальної установи Сумська загальноосвітня школа І-ІІІ ступенів № 26 м.Суми, Сумсбкої області", 
    "items": [
      {
        "description": "ЕНергосервіс будівлі Комунальної установи Сумська загальноосвітня школа І-ІІІ ступенів № 26 м. Суми, Сумської області", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Не відображене в інших розділах", 
          "id": "99999999-9"
        }, 
        "description_en": "Energy service of the public institution building of Sumy secondary school Nr 26", 
        "additionalClassifications": [
          {
            "scheme": "specialNorms", 
            "id": "000", 
            "description": "Специальные нормы и другое"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "40007", 
          "countryName": "Україна", 
          "streetAddress": "Охтирська, 21", 
          "region": "Сумська обл.", 
          "locality": "Суми"
        }, 
        "id": "660e66a4ffd0486f8f90041f36105f05"
      }, 
      {
        "description": "ЕНергосервіс будівлі Комунальної установи Сумська загальноосвітня школа І-ІІІ ступенів № 26 м. Суми, Сумської області", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Не відображене в інших розділах", 
          "id": "99999999-9"
        }, 
        "description_en": "Energy service of the public institution building of Sumy secondary school Nr 26", 
        "additionalClassifications": [
          {
            "scheme": "specialNorms", 
            "id": "000", 
            "description": "Специальные нормы и другое"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "40007", 
          "countryName": "Україна", 
          "streetAddress": "Охтирська, 21", 
          "region": "Сумська обл.", 
          "locality": "Суми"
        }, 
        "id": "156bb41b66574baaa0f4eeda9fdaf7a0"
      }
    ], 
    "suppliers": [
      {
        "contactPoint": {
          "email": "e.zhogan@ksteplo.com.ua", 
          "telephone": "+380933907440", 
          "name": "ТОВАРИСТВО З ОБМЕЖЕНОЮ ВІДПОВІДАЛЬНІСТЮ \"ЄВРОПЕЙСЬКА ЕНЕРГОСЕРВІСНА КОМПАНІЯ\""
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "40957551", 
          "legalName": "ТОВАРИСТВО З ОБМЕЖЕНОЮ ВІДПОВІДАЛЬНІСТЮ \"ЄВРОПЕЙСЬКА ЕНЕРГОСЕРВІСНА КОМПАНІЯ\""
        }, 
        "name": "ТОВАРИСТВО З ОБМЕЖЕНОЮ ВІДПОВІДАЛЬНІСТЮ \"ЄВРОПЕЙСЬКА ЕНЕРГОСЕРВІСНА КОМПАНІЯ\"", 
        "address": {
          "postalCode": "", 
          "countryName": "Україна", 
          "streetAddress": "01004, м.Київ, БЕССАРАБСЬКА ПЛОЩА, будинок 9/1 Б, офіс 2", 
          "region": "", 
          "locality": ""
        }
      }
    ], 
    "contractNumber": "17", 
    "period": {
      "startDate": "2018-05-23T09:37:39.577948+03:00", 
      "endDate": "2025-03-29T09:37:39.577948+03:00"
    }, 
    "value": {
      "yearlyPaymentsPercentage": 0.92, 
      "valueAddedTaxIncluded": true, 
      "currency": "UAH", 
      "amount": 1252688.01, 
      "contractDuration": {
        "days": 310, 
        "years": 6
      }, 
      "amountPerformance": 446471.27, 
      "annualCostsReduction": [
        0, 
        178997.04, 
        225643.72, 
        225643.72, 
        225643.72, 
        225643.72, 
        225643.72, 
        225643.72, 
        141782.47, 
        141782.47, 
        141782.47, 
        141782.47, 
        141782.47, 
        141782.47, 
        141782.47, 
        141782.47, 
        141782.47, 
        141782.47, 
        141782.47, 
        141782.47, 
        141782.47
      ]
    }, 
    "id": "05285a1b38494dcaaf0e47408f5913f9", 
    "procuringEntity": {
      "contactPoint": {
        "email": "e.zhogan@ksteplo.com.ua", 
        "telephone": "+380933907440", 
        "availableLanguage": "en", 
        "name": "ТОВАРИСТВО З ОБМЕЖЕНОЮ ВІДПОВІДАЛЬНІСТЮ \"ЄВРОПЕЙСЬКА ЕНЕРГОСЕРВІСНА КОМПАНІЯ\""
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "40957551", 
        "legalName": "ТОВАРИСТВО З ОБМЕЖЕНОЮ ВІДПОВІДАЛЬНІСТЮ \"ЄВРОПЕЙСЬКА ЕНЕРГОСЕРВІСНА КОМПАНІЯ\""
      }, 
      "name": "ТОВАРИСТВО З ОБМЕЖЕНОЮ ВІДПОВІДАЛЬНІСТЮ \"ЄВРОПЕЙСЬКА ЕНЕРГОСЕРВІСНА КОМПАНІЯ\"", 
      "address": {
        "postalCode": "", 
        "countryName": "Україна", 
        "streetAddress": "01004, м.Київ, БЕССАРАБСЬКА ПЛОЩА, будинок 9/1 Б, офіс 2", 
        "region": "", 
        "locality": ""
      }, 
      "additionalContactPoints": [
        {
          "name": "Державне управління справами2", 
          "telephone": "0440000001"
        }
      ]
    }, 
    "dateSigned": "2018-05-23T09:37:39.577948+03:00", 
    "contractID": "UA-2017-11-21-001567-c-a1", 
    "NBUdiscountRate": 0.135, 
    "owner": "broker", 
    "contractType": "esco", 
    "awardID": "29c01dd058c347f38e381f13d4a6a118", 
    "amountPaid": {
      "currency": "UAH", 
      "amount": 0, 
      "valueAddedTaxIncluded": true
    }, 
    "dateModified": "2018-05-23T09:37:42.085109+03:00", 
    "tender_id": "4f3f52df56274163b5cf22a00cd71478"
  }
}

