PATCH /api/2.4/contracts/05285a1b38494dcaaf0e47408f5913f9/milestones/74ed371ed450417caed14aaf2ab6687b?acc_token=a8a4bcfba9ca45edb7bd7c99e651804b HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 45
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "amountPaid": {
      "amount": 80000.0
    }
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "pending", 
    "description": "Milestone #2 of year 2019", 
    "sequenceNumber": 2, 
    "title": "Milestone #2 of year 2019", 
    "period": {
      "startDate": "2019-01-01T00:00:00+02:00", 
      "endDate": "2020-01-01T00:00:00+02:00"
    }, 
    "value": {
      "currency": "UAH", 
      "amount": 80000.0, 
      "valueAddedTaxIncluded": true
    }, 
    "id": "74ed371ed450417caed14aaf2ab6687b", 
    "date": "2018-05-23T09:37:44.772057+03:00", 
    "amountPaid": {
      "currency": "UAH", 
      "amount": 80000.0, 
      "valueAddedTaxIncluded": true
    }, 
    "dateModified": "2018-05-23T09:37:44.893590+03:00"
  }
}

