PATCH /api/2.4/contracts/05285a1b38494dcaaf0e47408f5913f9/milestones/981bd581b42b4e5ea9822d8af43d794d?acc_token=a8a4bcfba9ca45edb7bd7c99e651804b HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 38
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "value": {
      "amount": 80000
    }
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "scheduled", 
    "description": "Milestone #5 of year 2022", 
    "sequenceNumber": 5, 
    "title": "Milestone #5 of year 2022", 
    "period": {
      "startDate": "2022-01-01T00:00:00+02:00", 
      "endDate": "2022-05-23T09:37:39.577948+03:00"
    }, 
    "value": {
      "currency": "UAH", 
      "amount": 80000.0, 
      "valueAddedTaxIncluded": true
    }, 
    "id": "981bd581b42b4e5ea9822d8af43d794d", 
    "date": "2018-05-23T09:37:39.580154+03:00", 
    "amountPaid": {
      "currency": "UAH", 
      "amount": 0, 
      "valueAddedTaxIncluded": true
    }, 
    "dateModified": "2018-05-23T09:37:43.979305+03:00"
  }
}

