POST /api/2.4/contracts/05285a1b38494dcaaf0e47408f5913f9/documents?acc_token=20d3ef355ba342caaacd6590d712c6eb HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 215
Content-Type: multipart/form-data; boundary=----------a_BoUnDaRy731616923363$
Host: api-sandbox.openprocurement.org

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.4/contracts/05285a1b38494dcaaf0e47408f5913f9/documents/a9d0e984f4c141dfa8c3cf3b8a011d66
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "title": "contract_additional_docs.doc", 
    "url": "http://public.docs-sandbox.openprocurement.org/get/b3744f12d30c49c39ca898bf686165a9?KeyID=f988f514&Signature=RVmrw7tntELPSnp8cZ9KKT5NqIeb%2FBABgH%252B1cugmIMYkhfhY9vW7BHCkXtqK4T9XawphWI%252BCLlCnzvqUkIOPDw%253D%253D", 
    "format": "application/msword", 
    "documentOf": "contract", 
    "datePublished": "2018-05-15T15:33:45.328565+03:00", 
    "id": "a9d0e984f4c141dfa8c3cf3b8a011d66", 
    "dateModified": "2018-05-15T15:33:45.328590+03:00"
  }
}

