PUT /api/2.4/contracts/05285a1b38494dcaaf0e47408f5913f9/documents/97f13f29e49342d1bc9d1847f7b2ec4e?acc_token=a8a4bcfba9ca45edb7bd7c99e651804b HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 224
Content-Type: multipart/form-data; boundary=----------a_BoUnDaRy638414184005$
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "title": "contract_additional_docs.doc", 
    "url": "http://public.docs-sandbox.openprocurement.org/get/fedc409919d94c4bbb1f1194d2f0660f?KeyID=a4f1bd8c&Signature=CQVfQtIIB3NjY2kqIzsZufZ18vCdoUNq8K%2Fwv7jTPxZvDr8xx46AbYVOJ9JP88Vxae35Mz9vB1MIme6Yrug%252BCg%253D%253D", 
    "format": "application/msword", 
    "documentOf": "contract", 
    "datePublished": "2018-05-23T09:37:44.454405+03:00", 
    "id": "97f13f29e49342d1bc9d1847f7b2ec4e", 
    "dateModified": "2018-05-23T09:37:44.566759+03:00"
  }
}

