GET /api/2.4/contracts/05285a1b38494dcaaf0e47408f5913f9/changes HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": [
    {
      "status": "active", 
      "rationaleTypes": [
        "volumeCuts", 
        "priceReduction"
      ], 
      "rationale_en": "Contract change cause", 
      "dateSigned": "2018-05-15T15:33:44.935674+03:00", 
      "rationale": "Друга і третя поставка має бути розфасована", 
      "date": "2018-05-15T15:33:44.988077+03:00", 
      "id": "6a1ec221b3164000a0066c409a38eecd"
    }
  ]
}

