GET /api/2.4/contracts/05285a1b38494dcaaf0e47408f5913f9/changes HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": [
    {
      "status": "active", 
      "rationaleTypes": [
        "volumeCuts", 
        "priceReduction"
      ], 
      "rationale_en": "Contract change cause", 
      "dateSigned": "2018-05-23T09:37:44.046886+03:00", 
      "rationale": "Друга і третя поставка має бути розфасована", 
      "date": "2018-05-23T09:37:44.097032+03:00", 
      "id": "2012fa38548546dcbda1601ce90c91bb"
    }
  ]
}

